---

- name: GET all NMS-SM Deployments
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/security/deployments"
    method: GET
    status_code:
      - 200
      - 404
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_sm_publish_status
