---

- name: Process proxy-request-headers type
  block:

    - name: Set metadata
      set_fact:
        this_policy:
          metadata:
            labels:
              targetPolicyName: default
          systemMetadata:
            appliedOn: "backend"
          action:
            proxyHeaders:
              proxyDefaultHeadersToBackend: true
              proxyCustomHeadersToBackend: []

    - name: Merge User Data
      set_fact:
        policy_list: "{{ {'proxy-request-headers': [ this_policy | combine( policy.policy | default({}), recursive=True, list_merge='replace') ]} }}"

    - name: Update nms_acm_policy_bundle fact
      set_fact:
        nms_acm_policy_bundle: "{{ nms_acm_policy_bundle | default({}) | combine( policy_list, recursive=True) }}"

  when: policy.type == 'proxy-request-headers'

- name: Process apikey-authn type
  block:

    - name: Fail if required variables are not defined
      assert:
        that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
      loop:
        - "{{ policy.policy.data }}"

    - name: Set metadata
      set_fact:
        this_policy:
          metadata:
            labels:
              targetPolicyName: "default"
          systemMetadata:
            appliedOn: "inbound"
            context: "proxy"
          action:
            apiKeyName: "apikey"
            credentialForward: false
            suppliedIn: "header"
            errorReturnConditions:
              noMatch:
                returnCode: 401
              notSupplied:
                returnCode: 403
          data: []

    - name: Merge User Data
      set_fact:
        policy_list: "{{ {'apikey-authn': [ this_policy | combine( policy.policy | default({}), recursive=True, list_merge='replace') ]} }}"

    - name: Update nms_acm_policy_bundle fact
      set_fact:
        nms_acm_policy_bundle: "{{ nms_acm_policy_bundle | default({}) | combine( policy_list, recursive=True) }}"

  when: policy.type == 'apikey-authn'

- name: Process basic-authn type
  block:

    - name: Create Default Policy
      set_fact:
        this_policy:
          metadata:
            labels:
              targetPolicyName: "default"
          systemMetadata:
            appliedOn: "inbound"
            context: "proxy"
          action:
            credentialForward: "false"
            errorReturnConditions:
              notSupplied:
                grpcStatusCode: 16
                returnCode: 401
          data: []

    - name: Merge User Data
      set_fact:
        policy_list: "{{ {'basic-authn': [ this_policy | combine( policy.policy | default({}), recursive=True, list_merge='replace') ]} }}"

    - name: Update nms_acm_policy_bundle fact
      set_fact:
        nms_acm_policy_bundle: "{{ nms_acm_policy_bundle | default({}) | combine( policy_list, recursive=True) }}"

  when: policy.type == 'basic-authn'

- name: Process CORS type
  block:

    - name: Create Default Policy
      set_fact:
        this_policy:
          metadata:
            labels:
              targetPolicyName: "default"
          systemMetadata:
            appliedOn: "inbound"
            context: "proxy"
          action:
            allowCredentials: false
            allowHeaders: 
              - Accept
              - Authorization
              - Content-Type
              - Origin
              - X-Cache-Status
            allowMethods: 
              - GET
              - HEAD
              - DELETE
              - OPTIONS
              - PATCH
              - POST
              - PUT
              - TRACE
            allowOrigins:
              - exact: "*"
            exposeHeaders: []

    - name: Merge User Data
      set_fact:
        policy_list: "{{ {'cors': [ this_policy | combine( policy.policy | default({}), recursive=True, list_merge='replace') ]} }}"

    - name: Update nms_acm_policy_bundle fact
      set_fact:
        nms_acm_policy_bundle: "{{ nms_acm_policy_bundle | default({}) | combine( policy_list, recursive=True) }}"

  when: policy.type == 'cors'
