---
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nms_auth_type
    - nms_user_name
    - nms_user_passwd

- name: Setup Auth Headers
  set_fact:
    nms_auth_headers: "{{ nms_auth_headers | default({}) | combine({ 'Authorization': 'Basic ' + (( nms_user_name + ':' + nms_user_passwd)| b64encode ) }, recursive=True) }}"
  when: nms_auth_type == "basic"

