---

- name: Fail if required variables are not defined
  assert:
    that: ({{ item }} is defined) and ({{ item }} | string | length > 0)
  loop:
    - nms_fqdn
    - nms_validate_certs

- name: Set instance hostname
  set_fact:
    nms_instance_hostname: "{{ ansible_hostname }}"

- name: Ensure Agent is removed
  include_tasks: purge.yml
  when: nms_agent_state == "absent"

- name: Ensure Agent registration is removed
  block:

    - name: Purge NGINX Agent
      include_tasks: purge.yml

    - name: Un-Register the instance from NMS
      include_tasks: unregister.yml
  
  when: nms_agent_state == "reset" or nms_agent_state == "removed"

- name: Install the Agent
  include_tasks: install.yml
  when: nms_agent_state == "reset" or nms_agent_state == "present"

