---
- name: Restart Agent
  systemd:
    name: nginx-agent.service
    enabled: true
    state: restarted
  become: true

- name: Restart NGINX
  systemd:
    name: nginx.service
    enabled: true
    state: restarted
  become: true

- name: Restart Postgres
  systemd:
    name: postgresql.service
    enabled: true
    state: restarted
  become: true

- name: Restart DevPortal
  systemd:
    name: nginx-devportal.service
    enabled: true
    state: restarted
  become: true
