---

- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nms_fqdn
    - nms_api_version
    - nms_validate_certs
    - nms_instance_group

- name: Check NMS Authentication
  fail:
    msg: Missing Authentication headers 'nms_auth_headers', you need to include the 'nms_authenticate' role.
  when: nms_auth_headers is undefined

- name: GET NMS Instance Group status
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/instance-groups"
    method: GET
    status_code:
      - 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_instance_group_status

- name: Set nms_instance_group_refs fact
  set_fact:
    nms_instance_group_refs: "{{ nms_instance_group_refs | default({}) | combine({ item.name: (item | combine({ 'rel': nms_api_version ~ '/instance-groups/' ~ item.uid }))}, recursive=True) }}"
  loop: "{{ nms_instance_group_status.json['items'] }}"
  
- name: Create NMS Instance Group
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/instance-groups"
    method: POST
    body: "{{ nms_instance_group }}"
    body_format: json
    return_content: true
    status_code:
      - 201
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_post_response
  when: nms_instance_group_refs is undefined or nms_instance_group_refs[ nms_instance_group.name ] is undefined

- name: Patch NMS Instance Group
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_instance_group_refs[ nms_instance_group.name ].rel }}"
    method: PATCH
    body: "{{ nms_instance_group }}"
    body_format: json
    return_content: true
    status_code:
      - 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_put_response
  when: nms_instance_group_refs[ nms_instance_group.name ] is defined

- name: GET NMS Instance Group status
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/instance-groups"
    method: GET
    status_code:
      - 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_instance_group_status

- name: Set nms_instance_group_refs fact
  set_fact:
    nms_instance_group_refs: "{{ nms_instance_group_refs | default({}) | combine({ item.name: (item | combine({ 'rel': nms_api_version ~ '/instance-groups/' ~ item.uid }))}, recursive=True) }}"
  loop: "{{ nms_instance_group_status.json['items'] }}"

- name: GET NMS Instance Group status
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_instance_group_refs[ nms_instance_group.name ].rel }}"
    method: GET
    status_code: 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_instance_group_status

