---

- name: Fail if required variables are not defined
  assert:
    that: ({{ item }} is defined) and ({{ item }} | string | length > 0)
  loop:
    - nms_fqdn
    - nms_api_version
    - nms_validate_certs
    - nms_nim_certificate

- name: Check NMS Authentication
  fail:
    msg: Missing Authentication headers 'nms_auth_headers', you need to include the 'nms_authenticate' role.
  when: nms_auth_headers is undefined

- name: Upsert Certificate
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/certs/{{ nms_nim_certificate.name }}"
    method: PUT
    body: "{{ nms_nim_certificate }}"
    body_format: json
    return_content: true
    status_code:
      - 200
      - 201
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_response

- name: GET Certificate status
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/certs/{{ nms_nim_certificate.name }}"
    method: GET
    status_code: 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_nim_certificate_status
  
