---

- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nms_fqdn
    - nms_api_version
    - nms_validate_certs
    - nms_system

- name: Check NMS Authentication
  fail:
    msg: Missing Authentication headers 'nms_auth_headers', you need to include the 'nms_authenticate' role.
  when: nms_auth_headers is undefined

- name: GET NMS Systems Details
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/systems?hostname={{ nms_system.hostname }}"
    method: GET
    status_code:
      - 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_system_status
  failed_when: nms_system_status.json.count != 1

- name: Patch NMS System
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/systems/{{ nms_system_status.json['items'].0.uid }}"
    method: PATCH
    body: "{{ nms_system }}"
    body_format: json
    return_content: true
    status_code:
      - 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_response
  when: nms_system_status.json.count == 1

- name: GET NMS System status
  uri:
    url: "https://{{ nms_fqdn }}{{ nms_api_version }}/systems/{{ nms_system_status.json['items'].0.uid }}"
    method: GET
    status_code: 200
    validate_certs: "{{ nms_validate_certs | default(false) }}"
    headers: "{{ nms_auth_headers }}"
  register: nms_system_status

